name: Everyday

on:
  push:
    paths:
      - .github/workflows/everyday.yaml
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # Run this workflow every hour

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Fetch Everyday album
        run: |
          rm -f content/everyday/*.jpg
          ruby bin/download-lr.rb ${{ secrets.LIGHTROOM_SPACE_ID }} ${{ secrets.LIGHTROOM_ALBUM_ID }}
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add -A content/everyday/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync the everyday album"
            git push
          fi
